{% set version = '3.4.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nasaaccess
  version: {{ version|replace("-", "_") }}

source:

  url: https://github.com/nasa/NASAaccess/archive/V3.4.3.tar.gz
  sha256: 56a4c30935d08aad56c28fd23874ae9018528179eccd82528a305a1bf7ebbfe3

build:
  merge_build_host: True  # [win]
 
  number: 1
  
  noarch: generic
  
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-xml
    - r-getpass
    - r-httr
    - r-maptools
    - r-ncdf4
    - r-raster
    - r-rgdal
    - r-rgeos
    - r-shapefiles
    - r-sp
    - r-stringr

  run:
    - r-base
    - r-xml
    - r-getpass
    - r-httr
    - r-maptools
    - r-ncdf4
    - r-raster
    - r-rgdal
    - r-rgeos
    - r-shapefiles
    - r-sp
    - r-stringr

test:
  commands:
    
    - $R -e "library('NASAaccess')"           # [not win]
    - "\"%R%\" -e \"library('NASAaccess')\""  # [win]

about:
  home: https://github.com/nasa/NASAaccess
  license: NASA-1.3
  summary: NASAaccess software can generate gridded ascii tables of CMIP5 and CMIP6 climate data as well as earth observation remote sensing data (GPM, TRMM, GLDAS) needed to drive various hydrological models (e.g., SWAT, VIC, DHSVM, RHESSys, …etc.). The NASAaccess platform is available as software packages (i.e., conda and R packages) as well as an interactive format web-based environmental modeling application for earth observation data developed with the Tethys Platform.
  description: "The package assumes that users have already set up a registration account(s) with
    Earthdata login as well as authorizing NASA GES DISC data access. Please refer to
    \ <https://disc.gsfc.nasa.gov/data-access> for further details. Creating the '.netrc'
    file at the user machine Home directory and storing the user NASA GES DISC logging
    information in it is done automatically to execute the NASAaccess package commands.
    The GES DISC user registration access logging information will be processed by masking
    in the terminal on any major OS. Without providing GES DISC user registration access
    logging information, the user will receive 'You need to provide your Earthdata GES
    DISC login to proceed\u2026' message."
  license_family: OTHER
  license_file:
    - LICENSE
  doc_url: https://imohamme.github.io/NASAaccess/
  dev_url: https://github.com/imohamme/NASAaccess


extra:
  recipe-maintainers:
    - conda-forge/r
    - imohamme
